Config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(('User.urls', 'User'), namespace='UserApp')),
]

User/urls.py
from django.urls import path

from User.views import signup, signin, repetitions, home

app_name = 'users'

urlpatterns = [
    path('signup/', signup, name='Signup'),
    path('signin/', signin, name='Signin'),
    path('', home, name='Home'),
    path('repetitions/', repetitions, name='Repetitions'),
]

User/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=25, null=False, blank=False, unique=True)
    password = models.CharField(max_length=100)
    repetitions = models.IntegerField(default=10)  # Number of repeat for hashing

    def __str__(self):
        return f'{self.username}-{self.repetitions}'

User/forms.py
from django import forms
from User.models import User


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'name': 'password'}))
    confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'name': 'confirm_password'}))

    class Meta:
        model = User
        fields = ['username']

    def check_password(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("confirm_password")
        return password1 != password2

    def clean(self):
        cleaned_data = super().clean()
        if self.check_password():
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data


class UserSigninForm(forms.Form):

    username = forms.CharField(label='Username', widget=forms.TextInput())
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    repetitions = forms.IntegerField(widget=forms.HiddenInput, initial=10)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        if username and password:
            user = User.objects.filter(username=username).first()
            if not user:
                raise forms.ValidationError("Invalid username or password.")
        return cleaned_data

User/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from User.forms import UserCreationForm, UserSigninForm
from User.models import User
from Utilities import hasher
from django.views.decorators.csrf import csrf_exempt
import json


# Create your views here.


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            hasher.set_password(user, form.cleaned_data['password'])
            user.save()
            return redirect('UserApp:Signin')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


@csrf_exempt
def signin(request):
    if request.method == 'POST':
        jd = json.loads(request.body.decode('utf-8'))
        username = jd['username']
        client_password = jd['password']
        rep = jd['repetitions']
        try:
            user = User.objects.get(username=username)
            message = 'client_password (sent from front) :' + client_password + '<br>'
            message += 'server_password :' + hasher.hash_password(client_password) + '<br>'
            message += 'hashed_password in DB:' + user.password + '<br>'
            message += 'repetitions:' + str(user.repetitions) + '<br>'
            if hasher.check_password(user, client_password):
                user.password = client_password
                user.repetitions = rep - 1
                user.save()
                return HttpResponse("Login successful.<br>" + message)
            elif rep == 0:
                return HttpResponse('your OTP token does not valid anymore please set a new password')
            else:
                return HttpResponse("Invalid username or password.")
        except User.DoesNotExist:
            return HttpResponse("Invalid username or password.")
    else:
        return render(request, 'signin.html')


@csrf_exempt
def repetitions(request):
    if request.method == 'POST':
        jd = json.loads(request.body.decode('utf-8'))
        username = jd['username']
        try:
            user = User.objects.get(username=username)
            return JsonResponse({'repetitions': user.repetitions})
        except User.DoesNotExist:
            return JsonResponse({'repetitions': f'Invalid request-{username}'})
    return JsonResponse({'repetitions': 'Invalid request'})


def home(request):
    return render(request, 'home.html')

User/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<a href="{% url 'UserApp:Signin' %}">Signin</a>
<br>
<br>
<br>
<a href="{% url 'UserApp:Signup' %}">Signup</a>
</body>
</html>

User/templates/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>reset password</title>
</head>
<body>

</body>
</html>

User/templates/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">
<head>
    <title>Login</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script defer src="{% static 'js/Lamport(OTP).js' %}"></script>
</head>

<body>
<div>
    <h2>Sign In</h2>
    <p id="error" style="color: red"></p>
    <form id="signin-form" action="/signin/" method="post">
        {% csrf_token %}
        <div>
    <label for="id_username">Username:</label>



<input type="text" name="username" required="" id="id_username">

</div>

  <div>
    <label for="id_password">Password:</label>



<input type="password" name="password" required="" id="id_password">

      <input type="hidden" name="repetitions" value="10" id="id_repetitions">

</div>
        <button type="submit">Sign In</button>
    </form>
    <p>Don't have an account? <a href="/signup/">Sign Up here</a></p>
</div>
<div>
    <P id="result">

    </P>
</div>
</body>
</html>

User/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
<div>
    <h2>Sign Up</h2>
    {% for mess in message %}
    <p style="color: red">{{ mess }}</p>
    {% endfor %}
    <form method="post" action="{% url 'UserApp:Signup' %}">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit">Sign Up</button>
    </form>

    <p>Already have an account? <a href="{% url 'UserApp:Signin' %}">Sign In</a></p>
</div>
</body>
</html>